### PR TITLE
Replace {{foo}} with %{foo} in rspec1-compat

### PR DESCRIPTION
**Pull request by be9**

### CODE REVIEW

**Comment by nirvdrum** [comment]
If this could get applied that would be much appreciated.  Having my test console filled with useless output is making it hard to see where legitimate failures occur.

**Comment by zquestz** [comment]
I was just about to fork the project, do this fix, then submit a pull request. Seems someone beat me to the punch. Can someone please pull this in? My console would feel much nicer =)

**Comment by bsy** [comment]
+1, please consider applying this fix as it would be much appreciated!

**Comment by ml** [comment]
+1

**Comment by rud** [comment]
Here's hoping for this being pulled in soon

**Comment by levicole** [comment]
FWIW, you can use your own locale file and tell Remarkable to use it via:

``` ruby
Remarkable.add_locale('path/to/locale.yml')
```

Here is my Remarkable locale.yml:

https://gist.github.com/1622444

I hope this helps anyone as frustrated as I was that this never got pulled in for those less fortunate and working on legacy projects.

**Comment by pwoestelandt** [comment]
+1

**Comment by be9** [comment]
Okay, this is dead.

**Pull request closed without merging**
